import { ipc, store } from '@/electron'
import {
  Decoration,
  EditorView,
  ViewPlugin,
  WidgetType,
} from '@codemirror/view'
import {
  getNoteAttachmentExtension,
  isSupportedNoteAttachmentExtension,
  NOTE_ATTACHMENT_MAX_BYTES,
} from '~/shared/noteAttachments'
import {
  forgetImageUpload,
  imageUploadRanges,
  trackImageUpload,
} from './imageUploadRange'

const liveViews = new WeakSet<EditorView>()

function cleanAttachmentLabel(value: string): string {
  return value
    .replace(/[\[\]\\\r\n]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim() || 'attachment'
}

function getAttachmentExtension(file: File): string | null {
  const ext = getNoteAttachmentExtension(file.name)
  return isSupportedNoteAttachmentExtension(ext) ? ext : null
}

function insertMarkdown(view: EditorView, markdown: string, pos?: number) {
  const target = pos ?? view.state.selection.main.head
  view.dispatch({
    changes: { from: target, to: target, insert: markdown },
    selection: { anchor: target + markdown.length },
    scrollIntoView: true,
    userEvent: 'input',
  })
  view.focus()
}

async function insertAttachmentFile(
  view: EditorView,
  file: File,
  pos: number,
  noteId: () => number | undefined,
) {
  const ext = getAttachmentExtension(file)
  if (!ext || file.size > NOTE_ATTACHMENT_MAX_BYTES)
    return

  const id = crypto.randomUUID()
  const vault = store.preferences.get<string>('storage.vaultPath') ?? ''
  const targetNote = noteId()
  view.dispatch({ effects: trackImageUpload.of({ id, from: pos, text: '' }) })

  function finish(markdown: string) {
    if (
      !liveViews.has(view)
      || noteId() !== targetNote
      || vault !== (store.preferences.get<string>('storage.vaultPath') ?? '')
    ) {
      return
    }

    const range = view.state.field(imageUploadRanges, false)?.get(id)
    if (!range)
      return

    view.dispatch({
      changes: { from: range.from, to: range.to, insert: markdown },
      effects: forgetImageUpload.of(id),
    })
  }

  try {
    const arrayBuffer = await file.arrayBuffer()
    if (
      arrayBuffer.byteLength > NOTE_ATTACHMENT_MAX_BYTES
      || !liveViews.has(view)
      || noteId() !== targetNote
      || !view.state.field(imageUploadRanges, false)?.has(id)
      || vault !== (store.preferences.get<string>('storage.vaultPath') ?? '')
    ) {
      finish('')
      return
    }

    const url: string = await ipc.invoke('fs:notes-asset', {
      buffer: arrayBuffer,
      ext,
      vault,
    })

    const label = cleanAttachmentLabel(file.name)
    finish(`![${label}](${url})`)
  }
  catch (error) {
    console.error('[notes] Failed to save attachment', error)
    finish('')
  }
}

function getAttachmentFile(dataTransfer: DataTransfer | null): File | null {
  if (!dataTransfer)
    return null

  for (const file of Array.from(dataTransfer.files)) {
    if (
      getAttachmentExtension(file)
      && file.size <= NOTE_ATTACHMENT_MAX_BYTES
    ) {
      return file
    }
  }

  return null
}

class UploadWidget extends WidgetType {
  toDOM() {
    const element = document.createElement('span')
    element.textContent = 'Attaching file…'
    element.className = 'text-muted-foreground text-xs'
    return element
  }
}

export async function pickAndInsertAttachment(
  view: EditorView,
  noteId: () => number | undefined,
) {
  const vault = store.preferences.get<string>('storage.vaultPath') ?? ''
  const targetNote = noteId()
  const result = await ipc.invoke('fs:pick-note-attachment', { vault }) as
    | { status: 'saved', url: string, bytes: number, name: string }
    | { status: 'cancelled' | 'stale' | 'failed' }

  if (
    result.status !== 'saved'
    || noteId() !== targetNote
    || vault !== (store.preferences.get<string>('storage.vaultPath') ?? '')
  ) {
    view.focus()
    return
  }

  const label = cleanAttachmentLabel(result.name)
  insertMarkdown(view, `![${label}](${result.url})`)
}

export function createAttachmentInsert(noteId: () => number | undefined) {
  return [
    imageUploadRanges,
    ViewPlugin.define((view) => {
      liveViews.add(view)
      return { destroy: () => liveViews.delete(view) }
    }),
    EditorView.decorations.compute([imageUploadRanges], state =>
      Decoration.set(
        [...state.field(imageUploadRanges).values()].map(range =>
          Decoration.widget({ widget: new UploadWidget(), side: 1 }).range(
            range.from,
          ),
        ),
        true,
      )),
    EditorView.domEventHandlers({
      paste(event, view) {
        const file = getAttachmentFile(event.clipboardData)
        if (!file)
          return false

        // Prefer explicit text from the clipboard over a companion preview
        // image/file generated by another application.
        if (event.clipboardData?.getData('text/plain'))
          return false

        event.preventDefault()
        void insertAttachmentFile(
          view,
          file,
          view.state.selection.main.head,
          noteId,
        )
        return true
      },

      drop(event, view) {
        const file = getAttachmentFile(event.dataTransfer)
        if (!file)
          return false

        event.preventDefault()
        const pos
          = view.posAtCoords({ x: event.clientX, y: event.clientY })
            ?? view.state.selection.main.head
        void insertAttachmentFile(view, file, pos, noteId)
        return true
      },
    }),
  ]
}
